name: GODOCKERHUB

#main 브렌치에 push를 하거나 pull_request 를 할 때 동작

on:
  push:
    branches:["main"]

  pull_request:
    branches:["main"]

jobs:
  build:
    runs-on:ubuntu-latest
    steps:
      -uses: accounts/checkout@v3
      -names: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version:1.15
      -names: Build
        run: go build -v ./..