name: GODOCKERHUB

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    #GO 인 경우 -python으로 언어를 변경하면 이 부분을 수정하면 됩니다.
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - name: Build
        run: go build -v ./...

    #DOCKER HUB 에 이미지 만들어서 배포

    #도커 허브에 로그인
    #password는 절대로 하드코딩하면 안됩니다.
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with: 
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    #이미지를 업로드하고 도커허브에 배포
    - name: build and release to DockerHub
      env:
        NAME: byeoungkwon
        REPO: godockerhub
      run:
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest
        